# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productproduct_sale_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproduct',
            name='amount_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
