# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20171207_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productproduct',
            old_name='product_temlate',
            new_name='product_template',
        ),
    ]
