# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171208_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
