# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171209_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productproduct',
            old_name='count',
            new_name='count_product',
        ),
    ]
