# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171205_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='date_reserve',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
